package io.github.cdsap.parsetimeline.model

data class ExecutionNode(
    val id: String,
    val name: Name,
    val type: Int,
    val offset: Int,
    val duration: Long,
    val outcome: Int,
    val cacheabilityType: Int,
    val cacheabilityCategory: Int,
    val nonCacheableLabel: Int?,
    val nonCacheableReasonMessage: Int?,
    val planIndex: Int,
    val isOnCriticalPath: Boolean,
    val noActions: Boolean,
    val snapshottingInputsDuration: Long,
    val cacheOperationsDuration: Int?,
    val downloadingDependenciesDuration: Int?,
    val transformExecutionDuration: Int?,
    val taskActionExecutionDuration: Int?,
    val avoidanceSavingsDuration: Int?,
    val originBuildInvocationId: String?,
    val buildCacheKey: String?,
    val buildCacheOperations: List<BuildCacheOperation>,
    val buildCacheArtifact: BuildCacheArtifact?,
    val buildCacheOutcome: BuildCacheOutcome?,
    val workUnitCacheOutcome: String?,
    val upToDateMessages: UpToDateMessages?,
    val annotationProcessorExecutions: List<Any>,
    val javaToolchains: JavaToolchains?,
    val skipReasonMessage: String?,
    val hasTransformRequests: Boolean,
    val __typename: String
)
