name: Run Gradle on PRs
on:
  pull_request:
  push:
      branches: [main]
jobs:
    ktlint:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest]
                version: [17]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle ktlint
              run:  ./gradlew ktlintCheck
    build:
      timeout-minutes: 300
      strategy:
          matrix:
              os: [ubuntu-latest,macos-latest]
              version: [17]
              vendor: [zulu]
      runs-on: ${{ matrix.os }}
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                distribution:  ${{ matrix.vendor }}
                java-version:  ${{ matrix.version }}

          - name: Execute Gradle build
            run:  ./gradlew test
    fatbinary:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest]
                version: [17]
                vendor: [zulu, liberica]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Execute Gradle build
              run:  |
                ./gradlew :fatBinary
                ./timelineparser --mode generate-metrics --first-timeline resources/timeline1.json --second-timeline resources/timeline2.json --with-event-traces
                ./timelineparser --mode generate-models --timeline resources/timeline1.json
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: report-${{ matrix.vendor }}-${{ matrix.os }}--${{ matrix.version }}
                path: |
                   ./timeline1-parsed.json
                   ./metrics-timeline1-timeline2.csv
                   ./timeline1-event-traces.json
                   ./timeline2-event-traces.json

